import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BackgroundModel(props) {
  const { nodes, materials } = useGLTF("/blockbackground.glb");
  return (
    <group {...props} dispose={null} scale={0.2} position={[-21, -8.85, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot4.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plolt11.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot12.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot10.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot9.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot8.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot28.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot21.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot29.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot20.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot1.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot19.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot2.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot18.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot3.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot17.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot16.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot5.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot15.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot6.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot14.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot7.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot13.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot27.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot22.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot25.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot24.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot26.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plot23.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.housev1basicattic.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.housev1basic.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sidewalk.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_527.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object001.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse11.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse15.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse19.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse20.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse18.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse17.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse16.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse14.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse13.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse12.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse6.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse001.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse3.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse4.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse9.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse8.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse10.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse7.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse1.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse5.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse21.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse22.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse23.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_728.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse24.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse25.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhopuse27.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgroundhouse26.geometry}
        material={materials.Material_2}
        scale={0.584}
      />
    </group>
  );
}

useGLTF.preload("/blockbackground.glb");